version: '3'
services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=TFM_MONGO
      - MONGO_INITDB_ROOT_PASSWORD=TFM_MONGO_PASSWORD
    ports:
      - 27017:27017